# Generated by Django 5.0.3 on 2025-04-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='from_date',
            new_name='created_at',
        ),
    ]
